#!/bin/bash
clear
cyan='\e[0;36m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'
purple='\e[1;35m'

ping -c 1 google.com > /dev/null 2>&1
  if [ "$?" != 0 ]

then
    
    echo -e $red [Internet Connection]: OFFLINE!;
    echo -e $red You need to be connected to internet to be able to update fatrat;
    sleep 1
    exit 1

else
    echo -e $green [✔]::[Internet Connection]: connected!;
    echo ""
    sleep 1
echo -e $cyan "************************************"
echo -e $cyan "**  $green Updating Fatrat from Github $cyan **"
echo -e $cyan "************************************"
sleep 3
git pull

echo -e $cyan "*************************"
echo -e $cyan "**  $green Update Completed $cyan **"
echo -e $cyan "*************************"
fi
